// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NovelProject.Data;

#nullable disable

namespace NovelProject.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250711051359_ManualSaveMigration")]
    partial class ManualSaveMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.5");

            modelBuilder.Entity("NovelProject.Models.AchivmentsModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("IconPath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SceneId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ScenesModelid")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ScenesModelid");

                    b.ToTable("Achivments");
                });

            modelBuilder.Entity("NovelProject.Models.ActsModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("EndActText")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("EndPartId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("NextActId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("StartActText")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("StartPartId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Acts");
                });

            modelBuilder.Entity("NovelProject.Models.AnswersModel", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("asnwer_for_scene")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("id_scene")
                        .HasColumnType("INTEGER");

                    b.Property<int>("next_scene_id")
                        .HasColumnType("INTEGER");

                    b.HasKey("id");

                    b.ToTable("Answers");
                });

            modelBuilder.Entity("NovelProject.Models.PartsModel", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("act_id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("end_part_text")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("end_scene_id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("next_part_id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("start_part_text")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("start_scene_id")
                        .HasColumnType("INTEGER");

                    b.HasKey("id");

                    b.ToTable("Parts");
                });

            modelBuilder.Entity("NovelProject.Models.SaveFileModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("FirstSaveId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FirstSaveName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("LastManualSaveId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SecondSaveId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SecondSaveName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ThirdSaveId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ThirdSaveName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("SaveFile");
                });

            modelBuilder.Entity("NovelProject.Models.ScenesModel", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("additional_scene_img")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("answer")
                        .HasColumnType("INTEGER");

                    b.Property<string>("background_scene_img")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("id_next_scene")
                        .HasColumnType("INTEGER");

                    b.Property<int>("id_part")
                        .HasColumnType("INTEGER");

                    b.Property<string>("personage_scene_img")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("text_scene")
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.ToTable("Scenes");
                });

            modelBuilder.Entity("NovelProject.Models.UserAchivmentsModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("AchievedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("AchivmentId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsAchieved")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("UserAchivments");
                });

            modelBuilder.Entity("NovelProject.Models.UsersModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("GameNickname")
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("NovelProject.Models.AchivmentsModel", b =>
                {
                    b.HasOne("NovelProject.Models.ScenesModel", null)
                        .WithMany("achivmentsModels")
                        .HasForeignKey("ScenesModelid");
                });

            modelBuilder.Entity("NovelProject.Models.ScenesModel", b =>
                {
                    b.Navigation("achivmentsModels");
                });
#pragma warning restore 612, 618
        }
    }
}
