// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NovelProject.Data;

#nullable disable

namespace NovelProject.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.5");

            modelBuilder.Entity("NovelProject.Models.AnswersModel", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("asnwer_for_scene")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("id_scene")
                        .HasColumnType("INTEGER");

                    b.HasKey("id");

                    b.ToTable("Answers");
                });

            modelBuilder.Entity("NovelProject.Models.PartsModel", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("end_part_text")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("start_part_text")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.ToTable("Parts");
                });

            modelBuilder.Entity("NovelProject.Models.ScenesModel", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("answer")
                        .HasColumnType("INTEGER");

                    b.Property<string>("background_scene_img")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("id_next_scene")
                        .HasColumnType("INTEGER");

                    b.Property<int>("id_part")
                        .HasColumnType("INTEGER");

                    b.Property<string>("text_scene")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.ToTable("Scenes");
                });
#pragma warning restore 612, 618
        }
    }
}
